### ISSUE TITLE
bgp metric for NX-OS

### ISSUE THREAD

**Issue by henriots** [lwlcom/cisco_exporter#1]
Hello!

Is BGP metric disabled for NX-OS, because you couldn't test it or is it for some other reason? I forked your project and started debugging it and haven't ran into problems. Just have to enable check for NX-OS.

If it's for some other reason then I could try to fix it.

Anyways thanks alot for this project and I'll continue to work on it to support NX-OS, however as I'm starting to learn GO, so it will take some time.

**Comment by l3akage** [comment]
Hey,

we don't have BGP enabled on any NX-OS device, so i wasn't able to test it. Feel free to submit a Pull request

**Comment by l3akage** [comment]
Merged pull request f5caebf012efd8b48654325fd747351e63a1141e
Thanks
