### ISSUE TITLE
no key found  source="main.go:60"

### ISSUE THREAD

**Issue by gagostinho** [lwlcom/cisco_exporter#12]
hello guys how are you, i'm trying to install cisco_exporter and i'm facing a problem with the error below, and i don't know how to solve it since i still have little experience with linux,

./cisco_exporter -ssh.targets="10.10.3.254" -ssh.keyfile=cisco_exporter
INFO[0000] Loading config flags                          source="main.go:68"
FATA[0000] could not initialize exporter. could not initialize config for device ***.***.***.***: could not load ssh private key file: could not parse private key: ssh: no key found  source="main.go:60"

**Comment by l3akage** [comment]
Hey, the error means the exporter could not read your ssh private key. In your case it should be a file named "cisco_exporter" in the same directory as the cisco_exporter itself.

**Comment by gagostinho** [comment]
HI @l3akage , I located the cisco_exporter directory at /root/work/pkg/mod/github.com/lwlcom/
named as cisco_exporter@v0.0.0-20210407185844-1ac0e10064e3, and that's where I put the file and I continue to receive the same error.

**Comment by l3akage** [comment]
Your file "cisco_exporter" does not contain a valid ssh privat key. Maybe you copied the public key instead? Can you connect to your device via ssh? ssh 10.10.3.254 -i cisco_exporter
