### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by sajadonline** [lwlcom/cisco_exporter#15]
hi there.
when i want to install , i've a problem.

sajad:~$  go get -u github.com/lwlcom/cisco_exporter
# cd .; git clone -- https://gopkg.in/yaml.v2 /root/go/src/gopkg.in/yaml.v2
Cloning into '/root/go/src/gopkg.in/yaml.v2'...
fatal: unable to access 'https://gopkg.in/yaml.v2/': server certificate verification failed. CAfile: none CRLfile: none
package gopkg.in/yaml.v2: exit status 128

**Comment by l3akage** [comment]
Hey,
that looks like a problem with your local certificates, nothing to do with this repo.
Depending on your OS you could try updating ca-certificates

**Comment by sajadonline** [comment]
yes , my problem has been solved with this command

sudo apt-get install --reinstall ca-certificates
