### ISSUE TITLE
All commands timeout

### ISSUE THREAD

**Issue by jjo93sa** [lwlcom/cisco_exporter#23]
Been trying to get this exporter to work, but no matter what I try, I always get this result (logs from the exporter). I have disabled all features other than facts for now:
```
2023/06/24 14:11:46 Running command on <redacted>:22: show version
Timeout reached
time="2023-06-24T14:13:26Z" level=error msg="<redacted>: Timeout reached"
```
The switch in question is a `WS-C3560CG-8PC-S`  running `15.2(2)E10`., and I know that is old but I had hoped would still be supported.

Logging on the switch shows successful login, and then some time after a logout:

```
Jun 24 13:48:45.932 UTC: %SEC_LOGIN-5-LOGIN_SUCCESS: Login Success [user: prometheus] [Source: <redacted>] [localport: 22] at 13:48:45 UTC Sat Jun 24 2023
Jun 24 13:49:45.983 UTC: %SYS-6-LOGOUT: User prometheus has exited tty session 2(<redacted>)
```
I'm also able to login manually using the ssh credential and user name (prometheus), and then run the `show version`  and the other commands in the facts feature just fine, so I don't think it is a privilege level problem?

I'm at a loss, and would very much appreciate some clues or additional debugging steps I could take.

Thanks

**Comment by l3akage** [comment]
Could be [this](https://github.com/lwlcom/cisco_exporter/blob/2c2e4021969adfb7bd269c6275d5155b026d4714/connector/connection.go#L149) regex not matching. Does your cli look like "hostname#" ?

**Comment by jjo93sa** [comment]
That was it! I spent so long looking at this yesterday but didn't spot that regex. In my case, the user logging in isn't privileged so the prompt was: 
```
switch-name>
``` 
So I changed the line to:
```
re := regexp.MustCompile(`.+>\s?$`)
```
And everything just started working. Thanks so much.
